# Generated by Django 3.1.4 on 2020-12-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Images')),
                ('user', models.CharField(max_length=100)),
                ('user_profile', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
